openapi: 3.0.3
info:
  title: ChaufHER API — Contract Spec (Safety, Rides, Users, Drivers, SignalR)
  version: 2025-12-12
  description: |
    Partial OpenAPI spec covering safety event, ride state, user, and driver contracts.
    Includes REST endpoints and SignalR real-time event schemas for mobile app and web integration.
paths:
  /api/safety-events:
    post:
      summary: Trigger a safety event (panic)
      description: |
        Mobile clients POST a safety event. The API accepts an idempotency key to ensure
        safe retries. The server may accept the event immediately (200), queue it (202)
        for async processing, or return a conflict/validation error. Clients should
        follow the status returned and poll `/api/safety-events/{eventId}` for final state.
      operationId: createSafetyEvent
      parameters:
        - $ref: '#/components/parameters/Idempotency-Key'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SafetyEventRequest'
      responses:
        '200':
          description: Event acknowledged synchronously
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SafetyEventResponse'
        '202':
          description: Event accepted and queued for async processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SafetyEventResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Duplicate event detected (idempotent)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimit'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/safety-events/{eventId}:
    get:
      summary: Get safety event status
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current event status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SafetyEventResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/rides/{rideId}/status:
    get:
      summary: Get ride status (lightweight)
      parameters:
        - name: rideId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ride status
          content:
            application/json:
              schema:
                type: object
                properties:
                  rideId:
                    type: string
                  status:
                    type: string
                    example: en_route
                  updatedAt:
                    type: string
                    format: date-time
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/rides/{rideId}:
    get:
      summary: Get full ride details
      parameters:
        - name: rideId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ride details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RideDetails'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/rides:
    post:
      summary: Create a new ride request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRideRequest'
      responses:
        '201':
          description: Ride created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RideDetails'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/users/{userId}:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/drivers/{driverId}:
    get:
      summary: Get driver profile and availability
      parameters:
        - name: driverId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Driver profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    Idempotency-Key:
      name: Idempotency-Key
      in: header
      description: Client-generated idempotency key to deduplicate retries (UUID recommended)
      required: false
      schema:
        type: string

  schemas:
    SafetyEventRequest:
      type: object
      required:
        - tripId
        - userId
        - timestamp
        - location
      properties:
        idempotencyId:
          type: string
          description: Optional client idempotency identifier (also supported via header).
        tripId:
          type: string
          description: Server-assigned trip identifier (if active trip)
        userId:
          type: string
        timestamp:
          type: string
          format: date-time
        location:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
            accuracy:
              type: number
        deviceInfo:
          type: object
          properties:
            platform:
              type: string
            appVersion:
              type: string
        fallbackSms:
          type: boolean
          description: Whether SMS fallback is allowed (user opt-in)
        contacts:
          type: array
          items:
            type: string
          description: Optional emergency contact numbers

    SafetyEventResponse:
      type: object
      properties:
        eventId:
          type: string
        status:
          type: string
          enum:
            - queued
            - acknowledged
            - failed
            - duplicate
        message:
          type: string
        createdAt:
          type: string
          format: date-time
        retryAfter:
          type: integer
          description: Suggested retry in seconds (for 202 responses)

    RideDetails:
      type: object
      properties:
        rideId:
          type: string
        riderId:
          type: string
        driverId:
          type: string
        origin:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
            address:
              type: string
        destination:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
            address:
              type: string
        status:
          type: string
          enum: [pending, accepted, en_route, in_progress, completed, canceled]
        fare:
          type: number
        createdAt:
          type: string
          format: date-time
        eta:
          type: integer
          description: Estimated time of arrival in seconds

    CreateRideRequest:
      type: object
      required:
        - riderId
        - origin
        - destination
      properties:
        riderId:
          type: string
        origin:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
            address:
              type: string
        destination:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
            address:
              type: string
        scheduledTime:
          type: string
          format: date-time
          description: Optional scheduled ride time

    UserProfile:
      type: object
      properties:
        userId:
          type: string
        role:
          type: string
          enum: [rider, driver, admin]
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        profilePictureUrl:
          type: string
        verificationStatus:
          type: string
          enum: [pending, verified, rejected]
        createdAt:
          type: string
          format: date-time

    DriverProfile:
      type: object
      properties:
        driverId:
          type: string
        name:
          type: string
        phone:
          type: string
        rating:
          type: number
          format: double
        verificationStatus:
          type: string
          enum: [pending, verified, rejected]
        isAvailable:
          type: boolean
        currentLocation:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        totalRidesCompleted:
          type: integer

    RideUpdatedEvent:
      type: object
      description: SignalR event fired when ride state changes
      properties:
        rideId:
          type: string
        status:
          type: string
          enum: [pending, accepted, en_route, in_progress, completed, canceled]
        driverLocation:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        eta:
          type: integer
          description: Estimated time in seconds
        fare:
          type: number
        updatedAt:
          type: string
          format: date-time

    SafetyEventUpdateEvent:
      type: object
      description: SignalR event fired when safety event escalates or resolves
      properties:
        eventId:
          type: string
        status:
          type: string
          enum: [queued, acknowledged, escalated, resolved, failed]
        message:
          type: string
        escalationLevel:
          type: integer
          description: 0=initial, 1=ops review, 2=dispatch, 3=resolved
        assignedOps:
          type: string
          description: Ops staff member assigned to the event
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Authentication required or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    RateLimit:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

# Notes:
# - Clients SHOULD send an `Idempotency-Key` header or `idempotencyId` in the payload
#   to enable safe retries. The server will return 409 with the existing event when
#   a duplicate idempotency key is detected.
# - Server responses:
#   - 200: synchronous acknowledgement (rare for safety events)
#   - 202: accepted/queued for async processing (includes `retryAfter` optional)
#   - Poll /api/safety-events/{eventId} for final state (acknowledged/failed)
#
# SignalR Real-Time Events:
# - Hub: /hubs/rideevents (authenticated with JWT bearer token)
# - Event: ride.updated
#   - Fired when a ride state changes (accepted, en-route, in-progress, completed, canceled)
#   - Schema: RideUpdatedEvent (see schemas)
# - Event: safety.event.update
#   - Fired when a safety event escalates or resolves
#   - Schema: SafetyEventUpdateEvent (see schemas)